import React, { useMemo } from "react";
import type { Message } from "./types";
import ReactMarkdown from "react-markdown";
import rehypeHighlight from "rehype-highlight";
import { LogoMark } from "./LogoMark";

interface CodeBlockProps {
  language: string | undefined;
  value: string;
  children: React.ReactNode;
}

const CodeBlock: React.FC<CodeBlockProps> = ({ language, value, children }) => {
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(value);
    } catch {
      // ignore
    }
  };

  return (
    <div className="relative rounded-xl bg-[color:var(--vynthen-bg)] border border-[color:var(--vynthen-border)] my-4 text-[13px] overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 border-b border-[color:var(--vynthen-border)]">
        <span className="text-xs font-mono text-[color:var(--vynthen-fg-muted)] lowercase">{language || "text"}</span>
        <button
          type="button"
          onClick={handleCopy}
          className="text-xs text-[color:var(--vynthen-fg-muted)] hover:text-[color:var(--vynthen-fg)] transition-colors"
        >
          Copy
        </button>
      </div>
      <div className="p-4 overflow-x-auto">
        <pre>
          <code className={language ? `language-${language}` : undefined}>
            {children}
          </code>
        </pre>
      </div>
    </div>
  );
};

interface MessageBubbleProps {
  message: Message;
}

// Helper to extract raw text from complex React children generated by rehype
const extractText = (node: any): string => {
  if (typeof node === "string" || typeof node === "number") return String(node);
  if (Array.isArray(node)) return node.map(extractText).join("");
  if (node && node.props && node.props.children) {
    return extractText(node.props.children);
  }
  return "";
};

export const MessageBubble: React.FC<MessageBubbleProps> = ({ message }) => {
  const isUser = message.sender === "user";

  if (isUser) {
    return (
      <div className="flex justify-end mb-4">
        {/* User bubble: warm, soft, rounded — no harsh border */}
        <div className="max-w-[78%] rounded-2xl bg-[color:var(--vynthen-user-bubble)] px-5 py-3.5 text-[15px] leading-relaxed text-[color:var(--vynthen-fg)] shadow-sm">
          {message.content}
        </div>
      </div>
    );
  }

  const content = useMemo(() => message.content, [message.content]);

  return (
    // AI response: full width, no bubble — just clean prose like Claude
    <div className="flex items-start gap-3.5 mb-8 group">
      {/* Small V logo, vertically aligned to first line */}
      <div className="flex h-6 w-6 flex-none items-center justify-center mt-0.5 text-[color:var(--vynthen-fg-muted)]">
        <LogoMark className="w-4 h-4" interactive={true} />
      </div>
      <div className="prose-custom w-full max-w-none flex-1 text-[15px]">
        <ReactMarkdown
          rehypePlugins={[rehypeHighlight]}
          components={{
            code(props) {
              const { children, className, node, ...rest } = props;
              const match = /language-(\w+)/.exec(className || "");
              const value = extractText(children);
              const isInline = !match && !value.includes('\n');

              // Agent Mode 'thinking' block renderer
              if (match?.[1] === "thinking" || message.isAgent && value.includes("Step")) {
                const steps = value.split('\n').filter(s => s.trim().length > 0);
                return (
                  <div className="my-4 rounded-2xl bg-gradient-to-br from-[color:var(--vynthen-bg-secondary)] to-[color:var(--vynthen-bg)] border border-purple-500/20 p-4 shadow-sm relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-purple-500 to-blue-500 opacity-50"></div>
                    <div className="flex items-center gap-2 mb-3">
                      <div className="relative flex h-3 w-3">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-purple-400 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-3 w-3 bg-purple-500"></span>
                      </div>
                      <span className="text-xs font-semibold text-purple-400 uppercase tracking-wider">Agent Thinking</span>
                    </div>
                    <div className="flex flex-col gap-2">
                      {steps.map((step, idx) => (
                        <div key={idx} className="flex gap-3 text-[13px] text-[color:var(--vynthen-fg-muted)] animate-in fade-in slide-in-from-bottom-1" style={{ animationFillMode: 'both', animationDelay: `${Math.min(idx * 150, 1500)}ms` }}>
                          <span className="font-mono text-[10px] mt-1 opacity-50">❯</span>
                          <span className={`${idx === steps.length - 1 ? 'text-[color:var(--vynthen-fg)] font-medium' : ''}`}>{step.replace(/^\[|\]$/g, '')}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              }

              if (isInline) {
                return (
                  <code className="rounded bg-[color:var(--vynthen-bg-secondary)] border border-[color:var(--vynthen-border)] px-1.5 py-0.5 text-[0.85em] font-mono text-[color:var(--vynthen-fg)]">
                    {children}
                  </code>
                );
              }
              return <CodeBlock language={match?.[1]} value={value.replace(/\n$/, "")}>{children}</CodeBlock>;
            },
            img(props) {
              const { src, alt } = props;
              const safeSrc = src ? src.replace(/ /g, '%20') : '';
              return (
                <a href={safeSrc} target="_blank" rel="noopener noreferrer" className="block w-full max-w-sm my-4">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={safeSrc} alt={alt || "Generated Image"} className="w-full h-auto rounded-2xl shadow-md border border-[color:var(--vynthen-border)] object-cover bg-[color:var(--vynthen-bg-secondary)]" loading="lazy" />
                </a>
              );
            }
          }}
        >
          {content}
        </ReactMarkdown>
      </div>
    </div>
  );
};
